title: Codeinvoker
description: >-
    Codeinvoker website description
baseurl: ""
url: ""
twitter: codeinvoker
github: codeinvoker
facebook: codeinvoker

markdown: kramdown
plugins:
    - jekyll-feed

source: src
destination: dist

exclude:
    - assets
